version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: play_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: play_db

    ports:
      - "55432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  